GET http://localhost:3001/
###
GET http://localhost:3001/api/user/hello

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/login/
Content-Type: application/json

{
    "email":"test1@gmail.com",
    "password":"test1"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
    "firstName":"test2",
    "lastName":"test2",
    "email":"test2@gmail.com",
    "password":"test2",
    "age":30,
    "address":"kathmandu",
    "contact":"986769870",
    "role":"USER"

}

###
POST http://localhost:3001/api/menu-types
Content-Type: application/json

{
"userRole":"ADMIN",
"type": "desserts"
}

###
GET http://localhost:3001/api/menu-types

###
PUT http://localhost:3001/api/menu-types/4
Content-Type: application/json

{
   
    "userRole":"ADMIN",
    "type": "hot-drinks"
}

###
DELETE http://localhost:3001/api/menu-types/1
Content-Type: application/json

{
    "userRole": "ADMIN"
    
}

###
POST http://localhost:3001/api/menu-items
Content-Type: application/json

{
"userRole":"ADMIN",
"item_name": "Veg-biryani",
"item_price": 300,
"menuId": 2,
"availability": true,
"item_description": "With extra vegetables and cheese"
}

###
GET http://localhost:3001/api/menu-items

###

PUT http://localhost:3001/api/menu-items/3
Content-Type: application/json

{
   
    "userRole":"ADMIN",
    "item_price": 500,
    "item_description": "Delicious cheese pizza with extra cheese"
}

###
DELETE http://localhost:3001/api/menu-items/3
Content-Type: application/json

{
    "userRole": "ADMIN"
    
}